### PR TITLE
Add Blob.copy and Blob.copy_stream

### PR DESCRIPTION
**Pull request by tim-smart**

### CODE REVIEW

**Review by joeapearson — APPROVED** [review]
Thanks very much for the contribution; looks good.   Merging now.

**Comment by joeapearson** [comment]
@tim-smart let me know if master now works as you expect; if you're happy then we can cut a new release and publish to hex.

**Comment by tim-smart** [comment]
Our project is currently using this branch on our fork: https://github.com/arisechurch/elixir-azure/tree/api-changes

It has derived a bit, so switching back to your main branch will break things.

**Comment by joeapearson** [comment]
@tim-smart can you say a bit more about why you made the changes?  If there are compelling reasons to do so then I see no reason not to wrap your changes in to a non-backward-compatible future release (rather than having yet another fork, I'm sure you must have noticed the relative paucity of Azure clients for Elixir!)

**Comment by tim-smart** [comment]
Summary of changes:

- Clean up API surface to remove stutter. `Blob.put_blob` -> `Blob.put` for example.
- Streaming downloads to improve memory performance when downloading large files. This required a patch to telsa however, which hadn't been merged yet.
- Small usability fixes like adding extra options to some blob methods.

If you want to merge any of these in, then if I get some time I can extract them into a seperate branch.

**Comment by joeapearson** [comment]
Yep, these sound like nice improvements, possibly could make the `Blob.put_blob` -> `Blob.put` type changes backwards compatible with a `@deprecated` flag (I could do this quickly when you're able to provide an MR).

**Pull request merged**
